name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: input
    id: description
    attributes:
      label: Feature Description
      placeholder: e.g. Add dark mode toggle
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this feature useful?
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Potential Implementation
      description: Optional, share how you think this could be implemented
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots
